export const SHADOW_BG = '#00000095'
export const UI_EL_OPACITY = 0.5
export const ACTIVE_UI_EL_OPACITY = 0.8
export const CONTENT_AREA_WIDTH = '750px'
export const CONTENT_AREA_BORDER_RADIUS = '20px'
export const CONTENT_AREA_PADDING = '20px'
export const H1_MARGIN = '0 0 15px'
export const LAYOUT_EL_ZINDEX = 4
export const MAX_MOBILE_WIDTH = 768
export const TEXT_SHADOW_COLOR = 'rgb(34, 30, 31)'
export const TEXT_OUTLINE = `1px 1px 1px ${TEXT_SHADOW_COLOR}, -1px 1px 1px ${TEXT_SHADOW_COLOR}, 1px -1px 1px ${TEXT_SHADOW_COLOR}, -1px -1px 1px ${TEXT_SHADOW_COLOR}`
export const TEXT_SHADOW = `0px 0px 18px #000`
export const TEXT_REGULAR_OPACITY = 0.9