export const SHADOW_BG = '#00000095'
export const UI_EL_OPACITY = 0.5
export const ACTIVE_UI_EL_OPACITY = 0.8
export const CONTENT_AREA_WIDTH = '900px'
export const CONTENT_AREA_HEIGHT = '265px'
export const CONTENT_AREA_BORDER_RADIUS = '20px'
export const CONTENT_AREA_PADDING = '20px 30px'
export const H1_MARGIN = '0 0 15px'
export const LAYOUT_EL_ZINDEX = 4
export const MAX_MOBILE_WIDTH = 1023
export const TEXT_SHADOW_COLOR = 'rgb(34, 30, 31)'
export const TEXT_OUTLINE = `1px 1px 1px ${TEXT_SHADOW_COLOR}, -1px 1px 1px ${TEXT_SHADOW_COLOR}, 1px -1px 1px ${TEXT_SHADOW_COLOR}, -1px -1px 1px ${TEXT_SHADOW_COLOR}`
export const TEXT_SHADOW = `0px 0px 18px #000`
export const TEXT_REGULAR_OPACITY = 0.8
export const MIN_DESKTOP_HEIGHT = 600
export const MOBILE_CONTENT_WIDTH = 350
export const MODAL_SHADOW = 'rgba(12, 12, 12, 0.5)'
export const INPUT_BORDER_RADIUS = '5px'
export const INPUT_BORDER = '1px solid #B5B5B5'
export const INPUT_BG_COLOR = '#D9D9D9'
export const SKY_HEIGHT = 1550